sudo: false
language: node_js
node_js:
- stable
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: iwata0303@gmail.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: Q8ELprONVoL84r6VAZUFbCa3teOIPjvYJbVdIO/vwkT0FmkJWAMAGIw0Et7nF48uLMupRiSZ37zee9ZDclZJIv1+fugZdlF3zgjJG+oz0pVol+JWVQ3vW1ljiZfPt3G29Hzm3jKoNnt74E1NXy5rOAMrWKvFZVdDjghcQ7l8nLlbIT/QguB6XpsPDfteqlG1LIR5uAcjtlrnGo8ZZBNl/PxgM9GkEMu99cyoM4W6+tQYNnSEdCqxoWbT1VBP3WBsFnoDEYQtkXNYaUqG+NuGfDDfKrmV/319J1BIeEm6XCFcnhz8i6qcq24uV6XdJC8N/3VYYv7o3+hbIkGDVA1H5LpBQPKm3WDB3xi0INNCENmGeNRSGEWAdWEK0aBjd4nwVH8C9WzZg07hDbJkPlBSPrrp1FeTVzA3o7PZmor9Wl6bdL5xqCgsi3HxHGZZM2C45dm7tM9Z183tEktvo+9cZhjqlZrUR5mkGp1yAXsMvv1BIyXuavsOEIjWDvcHLa3LigIBpJit4ACsPZ4Qu7h77+zyyEWFHrM53v611mAEVuTXMlLe9ZMx2NhFJOCQjEEEgp3bTYbYcrKFs6DwZz5veGi2ineyKP9eovM5oDhVeatX4DN2UGpk+SeRSyqBh/eYN6UwqPLc7Ks96RZeDGrPMY7sHRj5PPTCJWpkSz20JJQ=
